# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: '088dadd6df3dd815708d1ad58fa27459bb3fdab82f0a4794cc7999f4e025f60c0f5ba29ff3f6af95fb7a3b30bce6cfaae0ef4452c4e1539055f571b7c929cc60'
  google_maps_api: <%= ENV["GOOGLE_MAPS_API"] %>
  bing_maps_api: <%= ENV["BING_MAPS_API"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_username: <%= ENV["SES_ACCESS_KEY_ID"] %>
  email_password: <%= ENV["SES_SECRET_ACCESS_KEY"] %>
  ga_tracker: <%= ENV['GA_TRACKER'] %>
  ga_api:
    service_account_email: <%= ENV['GOOGLE_SERVICE_ACCOUNT_EMAIL'] %>
    key_file: <%= ENV['GOOGLE_PRIVATE_KEY_FILE'] %>
    key_secret: notasecret
    profile_id: <%= ENV['GA_PROFILE_ID'] %>
    app_name: "GCES Development"
    app_version: "1.0"

test:
  secret_key_base: '088dadd6df3dd815708d1ad58fa27459bb3fdab82f0a4794cc7999f4e025f60c0f5ba29ff3f6af95fb7a3b30bce6cfaae0ef4452c4e1539055f571b7c929cc60'
  google_maps_api: <%= ENV["GOOGLE_MAPS_API"] %>
  bing_maps_api: <%= ENV["BING_MAPS_API"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_username: <%= ENV["SES_ACCESS_KEY_ID"] %>
  email_password: <%= ENV["SES_SECRET_ACCESS_KEY"] %>

staging:
  secret_key_base: '088dadd6df3dd815708d1ad58fa27459bb3fdab82f0a4794cc7999f4e025f60c0f5ba29ff3f6af95fb7a3b30bce6cfaae0ef4452c4e1539055f571b7c929cc60'
  google_maps_api: <%= ENV["GOOGLE_MAPS_API"] %>
  bing_maps_api: <%= ENV["BING_MAPS_API"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_username: <%= ENV["SES_ACCESS_KEY_ID"] %>
  email_password: <%= ENV["SES_SECRET_ACCESS_KEY"] %>
  ga_tracker: <%= ENV['GA_TRACKER'] %>

sales:
  secret_key_base: '088dadd6df3dd815708d1ad58fa27459bb3fdab82f0a4794cc7999f4e025f60c0f5ba29ff3f6af95fb7a3b30bce6cfaae0ef4452c4e1539055f571b7c929cc60'
  google_maps_api: <%= ENV["GOOGLE_MAPS_API"] %>
  bing_maps_api: <%= ENV["BING_MAPS_API"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_username: <%= ENV["SES_ACCESS_KEY_ID"] %>
  email_password: <%= ENV["SES_SECRET_ACCESS_KEY"] %>
  ga_tracker: <%= ENV['GA_TRACKER'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_maps_api: <%= ENV["GOOGLE_MAPS_API"] %>
  bing_maps_api: <%= ENV["BING_MAPS_API"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_username: <%= ENV["SES_ACCESS_KEY_ID"] %>
  email_password: <%= ENV["SES_SECRET_ACCESS_KEY"] %>
  ga_tracker: <%= ENV['GA_TRACKER'] %>
