class Certification < ActiveRecord::Base
  include Lookup

  SIX_SIGMA                               = 'SIX_SIGMA'
  PROFESSIONAL_ENGINEER_CIVIL             = 'PROFESSIONAL_ENGINEER_CIVIL'
  PROFESSIONAL_ENGINEER_MECHANICAL        = 'PROFESSIONAL_ENGINEER_MECHANICAL'
  PROFESSIONAL_ENGINEER_ELECTRICAL        = 'PROFESSIONAL_ENGINEER_ELECTRICAL'
  PROFESSIONAL_ENGINEER_SYSTEMS           = 'PROFESSIONAL_ENGINEER_SYSTEMS'
  PMI_SCHEDULING_PROFESSIONAL             = 'PMI_SCHEDULING_PROFESSIONAL'
  PMI_AGILE_CERT_PRACTITIONER             = 'PMI_AGILE_CERT_PRACTITIONER'
  PMI_RISK_PRACTITIONER                   = 'PMI_RISK_PRACTITIONER'
  CERTIFIED_PROFESSIONAL_ACCOUNTANT       = 'CERTIFIED_PROFESSIONAL_ACCOUNTANT'
  REGISTERED_ARCHITECT                    = 'REGISTERED_ARCHITECT'
  KNOWLEDGE_MANAGER_PROFESSIONAL          = 'KNOWLEDGE_MANAGER_PROFESSIONAL'
  EMERGENCY_MANAGEMENT_PROFESSIONAL       = 'EMERGENCY_MANAGEMENT_PROFESSIONAL'
  CERTIFIED_ETHICAL_HACKER                = 'CERTIFIED_ETHICAL_HACKER'
  INFORMATION_SYSTEMS_AUDITOR             = 'INFORMATION_SYSTEMS_AUDITOR'
  LAWYER                                  = 'LAWYER'
  CERTIFIED_PROFESSIONAL_SYSTEMS_ENGINEER = 'CERTIFIED_PROFESSIONAL_SYSTEMS_ENGINEER'
  CERTIFIED_PROFESSIONAL_LOGISTICIAN      = 'CERTIFIED_PROFESSIONAL_LOGISTICIAN'
  CERTIFICATION_TYPES = [SIX_SIGMA, PROFESSIONAL_ENGINEER_CIVIL,
                         PROFESSIONAL_ENGINEER_MECHANICAL, PROFESSIONAL_ENGINEER_ELECTRICAL,
                         PROFESSIONAL_ENGINEER_SYSTEMS, PMI_SCHEDULING_PROFESSIONAL,
                         PMI_AGILE_CERT_PRACTITIONER, PMI_RISK_PRACTITIONER,
                         CERTIFIED_PROFESSIONAL_ACCOUNTANT, REGISTERED_ARCHITECT,
                         KNOWLEDGE_MANAGER_PROFESSIONAL, EMERGENCY_MANAGEMENT_PROFESSIONAL,
                         CERTIFIED_ETHICAL_HACKER, INFORMATION_SYSTEMS_AUDITOR, LAWYER,
                         CERTIFIED_PROFESSIONAL_SYSTEMS_ENGINEER,
                         CERTIFIED_PROFESSIONAL_LOGISTICIAN].freeze
end
