class Position < ActiveRecord::Base
  CAPTURE_MANAGER = 'CAPTURE_MANAGER'
  CAPTURE_SUPPORT = 'CAPTURE_SUPPORT'
  PROPOSAL_MANAGER = 'PROPOSAL_MANAGER'
  VOLUME_LEAD = 'VOLUME_LEAD'
  TECHNICAL_VOLUME = 'TECHNICAL_VOLUME'
  MANAGEMENT_VOLUME = 'MANAGEMENT_VOLUME'
  PMI_IMF_SPECIALIST = 'PMI_IMF_SPECIALIST'
  COST_VOLUME = 'COST_VOLUME'
  PROGRAM_CONTRACTS_MANAGEMENT = 'PROGRAM_CONTRACTS_MANAGEMENT'
  PROJECT_COST_ANALYSIS = 'PROJECT_COST_ANALYSIS'
  SOLUTION_ARCHITECT = 'SOLUTION_ARCHITECT'
  PAST_PERFORMANCE_VOLUME = 'PAST_PERFORMANCE_VOLUME'
  RESUME_VOLUME = 'RESUME_VOLUME'
  MANUFACTURING_VOLUME = 'MANUFACTURING_VOLUME'
  EXECUTIVE_SUMMARY = 'EXECUTIVE_SUMMARY'
  SECURITY_VOLUME = 'SECURITY_VOLUME'
  SME_IT = 'SME_IT'
  SME_TELECOM = 'SME_TELECOM'
  SME_ELECTRONICS = 'SME_ELECTRONICS'
  SME_MECHANICAL = 'SME_MECHANICAL'
  SME_CIVIL = 'SME_CIVIL'
  SME_INDUSTRIAL = 'SME_INDUSTRIAL'
  SME_AEROSPACE = 'SME_AEROSPACE'
  SME_VEHICLE = 'SME_VEHICLE'
  SME_SERVICES = 'SME_SERVICES'
  SME_MANUFACTURING = 'SME_MANUFACTURING'
  SME_LOGISTICS = 'SME_LOGISTICS'
  SME_TRAINING = 'SME_TRAINING'
  SME_OTHER = 'SME_OTHER'
  SYSTEMS_ENGINEERING = 'SYSTEMS_ENGINEERING'
  PROGRAM_ARCHITECT = 'PROGRAM_ARCHITECT'
  BUSINESS_ARCHITECT = 'BUSINESS_ARCHITECT'
  PRODUCTION_MANAGER = 'PRODUCTION_MANAGER'
  VOLUME_CONTRIBUTER_AUTHOR = 'VOLUME_CONTRIBUTER_AUTHOR'
  STRATEGY = 'STRATEGY'
  PROPOSAL_COORDINATOR = 'PROPOSAL_COORDINATOR'
  GRAPHIC_DEVELOPMENT = 'GRAPHIC_DEVELOPMENT'
  TECHNICAL_WRITER = 'TECHNICAL_WRITER'
  COMPETITION_ANALYSIS = 'COMPETITION_ANALYSIS'
  PRICE_TO_WIN_ANALYSIS = 'PRICE_TO_WIN_ANALYSIS'
  REQUIREMENTS_ANALYIS = 'REQUIREMENTS_ANALYIS'
  DESKTOP_PUBLISHER = 'DESKTOP_PUBLISHER'
  IMP_IMS_SPECIALIST = 'IMP_IMS_SPECIALIST'
  SCHEDULER = 'SCHEDULER'
  PROPOSAL_WRITER = 'PROPOSAL_WRITER'
  PROPOSAL_EDITOR = 'PROPOSAL_EDITOR'
  RESUME_WRITER = 'RESUME_WRITER'
  DOLLAR_VALUE = 'DOLLAR_VALUE'

  POSITION_TYPES = [CAPTURE_MANAGER, CAPTURE_SUPPORT, PROPOSAL_MANAGER, VOLUME_LEAD,
                    TECHNICAL_VOLUME, MANAGEMENT_VOLUME, PMI_IMF_SPECIALIST, COST_VOLUME,
                    PROGRAM_CONTRACTS_MANAGEMENT,  PROJECT_COST_ANALYSIS, SOLUTION_ARCHITECT,
                    PAST_PERFORMANCE_VOLUME,  RESUME_VOLUME, MANUFACTURING_VOLUME,
                    EXECUTIVE_SUMMARY,  SECURITY_VOLUME, SME_IT, SME_TELECOM, SME_ELECTRONICS,
                    SME_MECHANICAL, SME_CIVIL, SME_INDUSTRIAL, SME_AEROSPACE, SME_VEHICLE,
                    SME_SERVICES, SME_MANUFACTURING, SME_LOGISTICS,  SME_TRAINING, SME_OTHER,
                    SYSTEMS_ENGINEERING,  PROGRAM_ARCHITECT, BUSINESS_ARCHITECT,
                    PRODUCTION_MANAGER,  VOLUME_CONTRIBUTER_AUTHOR, STRATEGY, PROPOSAL_COORDINATOR,
                    GRAPHIC_DEVELOPMENT, TECHNICAL_WRITER, COMPETITION_ANALYSIS,
                    PRICE_TO_WIN_ANALYSIS,  REQUIREMENTS_ANALYIS, DESKTOP_PUBLISHER,
                    IMP_IMS_SPECIALIST, SCHEDULER, PROPOSAL_WRITER,  PROPOSAL_EDITOR,
                    RESUME_WRITER, DOLLAR_VALUE].freeze

  validates :code, length: { maximum: 32 }, uniqueness: true, presence: true
end
